// Centralized icon map. Import here, use `<Icon name="..." />` everywhere.
// This keeps tree-shaking happy + lets us swap icon library later without touching pages.

import {
  // Navigation
  faCalendarDays,
  faMoneyBillWave,
  faHouse,
  faList,
  faClipboardList,
  faRotate,
  faBroom,
  faTicket,
  faFileInvoiceDollar,
  faChartLine,
  faScroll,
  faLandmark,

  // Header / system
  faRightFromBracket,
  faBell,
  faGear,
  faUser,
  faUserGroup,
  faKey,

  // Actions
  faMagnifyingGlass,
  faPlus,
  faMinus,
  faPen,
  faPenToSquare,
  faTrash,
  faEye,
  faCopy,
  faPrint,
  faDownload,
  faArrowUpFromBracket,
  faArrowRightFromBracket,
  faXmark,
  faCheck,
  faArrowLeft,
  faArrowRight,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faAngleDown,
  faSpinner,

  // Info / status
  faCircleInfo,
  faCircleCheck,
  faCircleExclamation,
  faCircleXmark,
  faTriangleExclamation,
  faClock,
  faHourglassHalf,
  faStar,
  faStarHalfStroke,

  // Property
  faBed,
  faBath,
  faRulerCombined,
  faWater,
  faUmbrellaBeach,
  faLocationDot,
  faMapLocationDot,
  faMapPin,
  faMountain,
  faTree,
  faKitchenSet,
  faCouch,
  faToiletPaper,
  faTableTennisPaddleBall,
  faDog,
  faChampagneGlasses,
  faPersonSwimming,

  // Money / commerce
  faMoneyBill,
  faMoneyBills,
  faCreditCard,
  faQrcode,
  faReceipt,
  faPercent,

  // Communication
  faPhone,
  faEnvelope,
  faMessage,
  faPaperPlane,

  // Time / calendar
  faCalendarCheck,
  faCalendarXmark,
  faCalendarPlus,
  faClockRotateLeft,

  // Misc
  faImage,
  faImages,
  faCloudArrowUp,
  faLink,
  faLinkSlash,
  faToolbox,
  faShieldHalved,
  faBolt,
  faFire,
  faSliders,
  faFilter,
  faSort,
  faEllipsisVertical,
  faArrowsRotate,
  faSquarePollVertical,
  faTags,
  faShop,
  faGlobe,
  faArrowUpRightFromSquare,
} from '@fortawesome/free-solid-svg-icons'

import { faLine, faFacebook, faAirbnb } from '@fortawesome/free-brands-svg-icons'

export const ICONS = {
  // Sidebar / nav
  calendar: faCalendarDays,
  money: faMoneyBillWave,
  home: faHouse,
  list: faList,
  bookings: faClipboardList,
  postpone: faRotate,
  broom: faBroom,
  ticket: faTicket,
  invoice: faFileInvoiceDollar,
  chart: faChartLine,
  history: faScroll,
  bank: faLandmark,

  // Header / system
  logout: faRightFromBracket,
  bell: faBell,
  gear: faGear,
  user: faUser,
  users: faUserGroup,
  key: faKey,

  // Actions
  search: faMagnifyingGlass,
  plus: faPlus,
  minus: faMinus,
  edit: faPen,
  editBox: faPenToSquare,
  trash: faTrash,
  eye: faEye,
  copy: faCopy,
  print: faPrint,
  download: faDownload,
  upload: faArrowUpFromBracket,
  exit: faArrowRightFromBracket,
  close: faXmark,
  check: faCheck,
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  chevronDown: faChevronDown,
  chevronUp: faChevronUp,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  caretDown: faAngleDown,
  spinner: faSpinner,

  // Info / status
  info: faCircleInfo,
  success: faCircleCheck,
  warning: faCircleExclamation,
  error: faCircleXmark,
  alert: faTriangleExclamation,
  clock: faClock,
  hourglass: faHourglassHalf,
  star: faStar,
  starHalf: faStarHalfStroke,

  // Property
  bed: faBed,
  bath: faBath,
  area: faRulerCombined,
  water: faWater,
  beach: faUmbrellaBeach,
  pin: faLocationDot,
  map: faMapLocationDot,
  mapPin: faMapPin,
  mountain: faMountain,
  tree: faTree,
  kitchen: faKitchenSet,
  couch: faCouch,
  toilet: faToiletPaper,
  pingPong: faTableTennisPaddleBall,
  pet: faDog,
  karaoke: faChampagneGlasses,
  swimmer: faPersonSwimming,

  // Money
  cash: faMoneyBill,
  cashStack: faMoneyBills,
  card: faCreditCard,
  qr: faQrcode,
  receipt: faReceipt,
  percent: faPercent,

  // Communication
  phone: faPhone,
  email: faEnvelope,
  message: faMessage,
  send: faPaperPlane,

  // Time
  calendarCheck: faCalendarCheck,
  calendarX: faCalendarXmark,
  calendarPlus: faCalendarPlus,
  rewind: faClockRotateLeft,

  // Misc
  image: faImage,
  images: faImages,
  cloudUpload: faCloudArrowUp,
  link: faLink,
  unlink: faLinkSlash,
  toolbox: faToolbox,
  shield: faShieldHalved,
  bolt: faBolt,
  fire: faFire,
  sliders: faSliders,
  filter: faFilter,
  sort: faSort,
  more: faEllipsisVertical,
  refresh: faArrowsRotate,
  dashboard: faSquarePollVertical,
  tags: faTags,
  shop: faShop,
  globe: faGlobe,
  external: faArrowUpRightFromSquare,

  // Brands
  line: faLine,
  facebook: faFacebook,
  airbnb: faAirbnb,
} as const

export type IconName = keyof typeof ICONS
