// Centralized icon map. Import here, use `<Icon name="..." />` everywhere.
// This keeps tree-shaking happy + lets us swap icon library later without touching pages.

import {
  // Navigation
  faCalendarDays,
  faMoneyBillWave,
  faHouse,
  faList,
  faClipboardList,
  faRotate,
  faBroom,
  faTicket,
  faFileInvoiceDollar,
  faChartLine,
  faScroll,
  faLandmark,

  // Header / system
  faRightFromBracket,
  faBell,
  faGear,
  faUser,
  faUserGroup,
  faKey,
  faLock,

  // Actions
  faMagnifyingGlass,
  faPlus,
  faMinus,
  faPen,
  faPenToSquare,
  faTrash,
  faEye,
  faCopy,
  faPrint,
  faDownload,
  faArrowUpFromBracket,
  faArrowRightFromBracket,
  faXmark,
  faCheck,
  faArrowLeft,
  faArrowRight,
  faChevronDown,
  faChevronUp,
  faChevronLeft,
  faChevronRight,
  faAngleDown,
  faSpinner,
  faBars,

  // Info / status
  faCircleInfo,
  faCircleCheck,
  faCircleExclamation,
  faCircleXmark,
  faTriangleExclamation,
  faClock,
  faHourglassHalf,
  faStar,
  faStarHalfStroke,

  // Property
  faBed,
  faBath,
  faRulerCombined,
  faWater,
  faUmbrellaBeach,
  faLocationDot,
  faMapLocationDot,
  faMapPin,
  faMountain,
  faTree,
  faKitchenSet,
  faCouch,
  faToiletPaper,
  faTableTennisPaddleBall,
  faDog,
  faChampagneGlasses,
  faPersonSwimming,

  // Property types (landing tiles)
  faBuilding,
  faHotel,
  faShip,
  faCaravan,
  faCampground,
  faIgloo,
  faChurch,
  faSchool,
  faPersonShelter,
  faHouseUser,
  faSailboat,
  faSnowflake,
  faTents,

  // Amenities
  faWifi,
  faCar,
  faTv,
  faShower,
  faMugSaucer,
  faSquareParking,
  faDumbbell,
  faSpa,
  faHotTubPerson,
  faMusic,
  faGamepad,
  faSmoking,
  faBellConcierge,
  faShirt,
  faTemperatureHigh,
  faFan,
  faFireExtinguisher,
  faBriefcase,
  faChalkboard,
  faGlassWater,
  faMicrophone,
  faWind,
  faFutbol,

  // Money / commerce
  faMoneyBill,
  faMoneyBills,
  faCreditCard,
  faQrcode,
  faReceipt,
  faPercent,

  // Communication
  faPhone,
  faEnvelope,
  faMessage,
  faPaperPlane,

  // Time / calendar
  faCalendarCheck,
  faCalendarXmark,
  faCalendarPlus,
  faClockRotateLeft,

  // Misc
  faImage,
  faImages,
  faCloudArrowUp,
  faLink,
  faLinkSlash,
  faToolbox,
  faShieldHalved,
  faBolt,
  faFire,
  faSliders,
  faFilter,
  faSort,
  faEllipsisVertical,
  faArrowsRotate,
  faSquarePollVertical,
  faTags,
  faShop,
  faGlobe,
  faArrowUpRightFromSquare,
} from '@fortawesome/free-solid-svg-icons'

import { faLine, faFacebook, faAirbnb } from '@fortawesome/free-brands-svg-icons'

export const ICONS = {
  // Sidebar / nav
  calendar: faCalendarDays,
  money: faMoneyBillWave,
  home: faHouse,
  list: faList,
  bookings: faClipboardList,
  postpone: faRotate,
  broom: faBroom,
  ticket: faTicket,
  invoice: faFileInvoiceDollar,
  chart: faChartLine,
  history: faScroll,
  bank: faLandmark,

  // Header / system
  logout: faRightFromBracket,
  bell: faBell,
  gear: faGear,
  user: faUser,
  users: faUserGroup,
  key: faKey,
  lock: faLock,

  // Actions
  search: faMagnifyingGlass,
  plus: faPlus,
  minus: faMinus,
  edit: faPen,
  editBox: faPenToSquare,
  trash: faTrash,
  eye: faEye,
  copy: faCopy,
  print: faPrint,
  download: faDownload,
  upload: faArrowUpFromBracket,
  exit: faArrowRightFromBracket,
  close: faXmark,
  check: faCheck,
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  chevronDown: faChevronDown,
  chevronUp: faChevronUp,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  caretDown: faAngleDown,
  spinner: faSpinner,
  menu: faBars,

  // Info / status
  info: faCircleInfo,
  success: faCircleCheck,
  warning: faCircleExclamation,
  error: faCircleXmark,
  alert: faTriangleExclamation,
  clock: faClock,
  hourglass: faHourglassHalf,
  star: faStar,
  starHalf: faStarHalfStroke,

  // Property
  bed: faBed,
  bath: faBath,
  area: faRulerCombined,
  water: faWater,
  beach: faUmbrellaBeach,
  pin: faLocationDot,
  map: faMapLocationDot,
  mapPin: faMapPin,
  mountain: faMountain,
  tree: faTree,
  kitchen: faKitchenSet,
  couch: faCouch,
  toilet: faToiletPaper,
  pingPong: faTableTennisPaddleBall,
  pet: faDog,
  karaoke: faChampagneGlasses,
  swimmer: faPersonSwimming,

  // Property type icons (used by the new-listing tile grid)
  building: faBuilding,
  hotel: faHotel,
  ship: faShip,
  sailboat: faSailboat,
  caravan: faCaravan,
  campground: faCampground,
  tents: faTents,
  igloo: faIgloo,
  church: faChurch,
  school: faSchool,
  shelter: faPersonShelter,
  houseUser: faHouseUser,
  snowflake: faSnowflake,

  // Amenities (used by the amenity-picker step)
  wifi: faWifi,
  car: faCar,
  tv: faTv,
  shower: faShower,
  coffee: faMugSaucer,
  parking: faSquareParking,
  dumbbell: faDumbbell,
  spa: faSpa,
  hotTub: faHotTubPerson,
  music: faMusic,
  gamepad: faGamepad,
  smoking: faSmoking,
  concierge: faBellConcierge,
  shirt: faShirt,
  ac: faTemperatureHigh,
  fan: faFan,
  fireExt: faFireExtinguisher,
  briefcase: faBriefcase,
  chalkboard: faChalkboard,
  glassWater: faGlassWater,
  microphone: faMicrophone,
  wind: faWind,
  ball: faFutbol,

  // Money
  cash: faMoneyBill,
  cashStack: faMoneyBills,
  card: faCreditCard,
  qr: faQrcode,
  receipt: faReceipt,
  percent: faPercent,

  // Communication
  phone: faPhone,
  email: faEnvelope,
  message: faMessage,
  send: faPaperPlane,

  // Time
  calendarCheck: faCalendarCheck,
  calendarX: faCalendarXmark,
  calendarPlus: faCalendarPlus,
  rewind: faClockRotateLeft,

  // Misc
  image: faImage,
  images: faImages,
  cloudUpload: faCloudArrowUp,
  link: faLink,
  unlink: faLinkSlash,
  toolbox: faToolbox,
  shield: faShieldHalved,
  bolt: faBolt,
  fire: faFire,
  sliders: faSliders,
  filter: faFilter,
  sort: faSort,
  more: faEllipsisVertical,
  refresh: faArrowsRotate,
  dashboard: faSquarePollVertical,
  tags: faTags,
  shop: faShop,
  globe: faGlobe,
  external: faArrowUpRightFromSquare,

  // Brands
  line: faLine,
  facebook: faFacebook,
  airbnb: faAirbnb,
} as const

export type IconName = keyof typeof ICONS
